name: GetInfo
version: 0.0
api-version: 1.20
main: com.bubbamc.GetInfo
author: Jason
description: Get info about a block

commands:
    info:
        usage: /<command>
        description: gives you info wand